spring:
  activemq:
    broker-url: ${broker.url}
    user: admin
    password: admin
    in-memory: false
    non-blocking-redelivery: true
logging:
  level:
    root: info
management:
  health:
    jms:
      enabled: true